services:
  # Backend API service (now Docker‑based)
  - type: web
    name: supervity-backend
    runtime: docker       # use a Dockerfile instead of the built‑in Python runtime :contentReference[oaicite:0]{index=0}
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    # any startup command is handled by your Dockerfile's CMD; you can override it via `dockerCommand` if needed
    envVars:
      - key: LLM_MODEL
        value: gemini-2.5-pro-preview-03-25
      - key: LLM_TEMPERATURE
        value: "0.63"
      - key: GEMINI_API_KEY
        sync: false

  # Frontend static site
  - type: web
    name: supervity-frontend
    runtime: static
    buildCommand: cd account-research-ui && npm install && npm run build
    staticPublishPath: account-research-ui/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: supervity-backend
          type: web
          property: host
