services:
  # Backend API service
  - type: web
    name: supervity-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: LLM_MODEL
        value: gemini-2.5-pro-preview-03-25
      - key: LLM_TEMPERATURE
        value: "0.63"
      - key: GEMINI_API_KEY
        sync: false
    # Use Render's apt packages feature
    packages:
      - build-essential
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-cffi
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgdk-pixbuf2.0-0
      - libffi-dev
      - shared-mime-info

  # Frontend static site
  - type: web
    name: supervity-frontend
    runtime: static
    buildCommand: cd account-research-ui && npm install && npm run build
    staticPublishPath: account-research-ui/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: supervity-backend
          type: web
          property: host
