services:
  # Backend API service
  - type: web
    name: supervity-backend
    env: python
    region: oregon  # Choose your preferred region
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn app.api.main:app --host 0.0.0.0 --port $PORT
    plan: free  # Adjust as needed
    healthCheckPath: /
    envVars:
      - key: LLM_MODEL
        value: gemini-2.5-pro-preview-03-25
      - key: LLM_TEMPERATURE
        value: 0.63
      - key: GEMINI_API_KEY
        sync: false  # This will prompt for the value during deployment
    # Use Render's apt packages feature instead of apt-get in build script
    packages:
      - build-essential
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-cffi
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgdk-pixbuf2.0-0
      - libffi-dev
      - shared-mime-info

  # Frontend static site
  - type: web
    name: supervity-frontend
    env: static
    # region is not allowed for static sites
    buildCommand: cd account-research-ui && npm install && npm run build
    staticPublishPath: account-research-ui/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          name: supervity-backend
          type: web
          property: host  # Changed from url to host

# Ensure that the backend is deployed before the frontend
envVarGroups:
  - name: backend-env
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # This will prompt for the value during deployment 